### ISSUE TITLE
[amundsen-kube-helm] helm chart:  neo4j deployment may have resources in the wrong place?

### ISSUE THREAD

**Issue by jdavidheiser** [lyft/amundsen#328] opened 2020-03-11 22:25 UTC
I am trying to launch amundsen from the Kube helm chart, by first rendering the templates manually and then copying the results into our internal Kube framework, and I got an error on the presence of a resource field in the wrong place.  In the template, the line in question is:

https://github.com/lyft/amundsen/blob/8b794ecb0f9e31cf279e9b2576911d707101c54d/amundsen-kube-helm/templates/helm/neo4j/templates/deployment.yaml#L82

I think this should probably be moved up to the container section.

**Comment by feng-tao** [comment] 2020-03-14 04:10
cc @samshuster @javamonkey79

**Comment by samshuster** [comment] 2020-03-16 16:06
just a wild guess, is this due to a helm version issue? What version of helm are you using @jdavidheiser?

**Comment by javamonkey79** [comment] 2020-03-16 16:58
@jdavidheiser yeah, I confirmed it; I was actually getting a warning in intellij, but, ignored it. A quick pass on the docs confirms the def is out of place:

1. pod spec -> https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#podspec-v1-core -> has container, but, no resource element
2. container spec -> https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#container-v1-core -> container has a resource element

We didn't do this work, so, I think that's why we didn't notice it. @lukelowery this was from your additions, so, be aware this could cause issues on your setup. 

Finally, @feng-tao ; I'm working on a fairly big update, so, go ahead and assign this to me and tag the issue with k8s tag.

**Comment by javamonkey79** [comment] 2020-03-16 17:38
You can deny this request if you want @feng-tao but, it would be nice to edit the title of this to include [amundsen-kube-helm] at the beginning; I realize it is already tagged, but, it would help me... I would do it, but, I have very limited privileges.

**Comment by javamonkey79** [comment] 2020-03-24 22:51
This is done with https://github.com/lyft/amundsen/pull/336

**Comment by javamonkey79** [comment] 2020-03-24 22:52
I can't close it, but, it's done @feng-tao

**Comment by javamonkey79** [comment] 2020-03-24 22:52
@jdavidheiser feel free to confirm...

**Comment by feng-tao** [comment] 2020-03-24 22:52
thanks @javamonkey79

**Closed by feng-tao** 2020-03-24 22:52 UTC
Labels: k8s, keep fresh
