### ISSUE TITLE
UNEDITABLE_SCHEMAS not working

### ISSUE THREAD

**Issue by jdavidheiser** [lyft/amundsen#507] opened 2020-06-11 21:04 UTC
##  Expected Behavior
When adding database schemas to `UNEDITABLE_SCHEMAS` (e.g. `UNEDITABLE_SCHEMAS = set(["public", "raw"])` in a custom config Python class, and using that config file by setting the environment variable `FRONTEND_SVC_CONFIG_MODULE_CLASS`, editing table descriptions and column descriptions for matching schemas should be disabled.  

## Current Behavior
The configuration option appears to have no effect.

I am not sure whether we need to rebuild the entire app, replacing config.py, or simply add this custom config file and set it up for wsgi using the environment variable.

https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/configuration.md#flask seems to imply we can set the variable without rebuilding the app, and https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/flask_config.md implies we need to rebuild the application.

## Context
We want to disable editing for descriptions because the source of truth is under source control, so either getting this configuration working or using another method to disable edits would work.

## Your Environment
* Amunsen version used: frontend from hash 6da701505c070b31a612f7e48c1917d9835b8e26
* Data warehouse stores: Neo4j
* Deployment (k8s or native): Kubernetes

**Comment by feng-tao** [comment] 2020-06-11 21:48
cc @ttannis is this feature ready in master? I thought we are still building it. But will let you chimein :)

**Comment by ttannis** [comment] 2020-06-11 22:43
We built the feature a while ago, at one point some schemas in Amundsen were uneditable. This is a regression, and I think it happened when we did the redesign work. The new `TableDetail` page isn't checking for whether something will be editable or not. 

I'll prioritize fixing this before the next release, which will come as soon as we complete our remaining priorities for dashboard features.

**Comment by feng-tao** [comment] 2020-06-11 22:47
now i remember ... This applies to the redshift schema which are all full rebuild table.

**Comment by feng-tao** [comment] 2020-06-11 22:48
@ttannis  with the new non editable schemas at Lyft, are you plan to leverage the existing one or refactor it for the new upcoming use case?

**Comment by ttannis** [comment] 2020-06-12 18:13
> @ttannis with the new non editable schemas at Lyft, are you plan to leverage the existing one or refactor it for the new upcoming use case?

It would depend on how flexible we need it to be to cover our updated use case, so I can't speak on the need for a refactor yet until we get the final sign off on the expectations for our use case.

**Comment by dikshathakur3119** [comment] 2020-06-25 20:19
After discussion with team, here are two ways in which we can approach uneditable description :

**Approach 1 : Frontend :** Defining Pattern Regex statements in frontend application to identify any tables following given pattern should have uneditable table and column description. For simpler cases, we can use 'UNEDITABLE_SCHEMA' variable defined in config file to make all tables uneditable from a given schema. It will be faster to implement.

**Approach 2 : Backend :** If a table's description is editable or not, this information should flow from metadata builder service. Adding an attribute 'isEditable' to TABLEMETADATA class, and setting 'isEditable' depending on specific pattern or schema name defined in backend service itself. This eliminates any processing at front-end, this approach is more scaleable. It will take more time to implement and would also require some modifications at frontend, since currently frontend is reading UNEDITABLE from config file.

Please share your views here, which approach is preferred and why? Please share if you have any other ideas to solve this.

**Comment by feng-tao** [comment] 2020-06-25 21:16
I wonder whether it is conflicted to be either approach 1 or approach 2. Should we do approach 1 as short term given we have already supported the flag but it is broken, then do approach 2 as a follow up/long run? @jinhyukchang @ttannis thought?

Also for approach 2, I think it should be an attribute on the description node not on table metadata given table metadata has not awareness on the description whether it is manual or programmatic. The flow I could think of would be all description node has `isEditable` attribute to be false during ingestion, then for certain cases(like Lyft, we put uneditable descriptions for event tables), we set the attribute to be true for event table/column descriptions. Then in metadata description endpoint, we always check whether the field is set and only update if the field is set with value as false. cc @jinhyukchang in case you feel differently.

**Comment by ttannis** [comment] 2020-06-25 21:42
My thoughts are that Approach 1 would be a sufficient fix and that Approach 2 would be best long term because it would help support more fine grained cases. For example, we (Lyft) have an upcoming requirement to make owners un-editable for specific tables as well.  So moving towards support for `is_editable` attributes on specific metadata would be ideal for that implementation as well.

**Comment by dikshathakur3119** [comment] 2020-06-25 22:55
Okay, for now I will apply approach 1 to fix this. Thank you for your feedbacks.

**Comment by jonhehir** [comment] 2020-07-13 16:32
It looks like this works and can be closed now. Thank you so much, @dikshathakur3119!

**Closed** 2020-07-13 16:40 UTC
Labels: Project: Frontend, Status: Accepted, Type: Bug :beetle:, keep fresh
