### ISSUE TITLE
feature: Dashboard descriptions do not honor Markdown formatting

### ISSUE THREAD

**Issue by jonhehir** [lyft/amundsen#543] opened 2020-07-09 17:07 UTC
## Expected Behavior

Markdown formatting in dashboard descriptions is rendered appropriately, just like for table descriptions.

## Current Behavior

These descriptions show up as plain-text.

## Screenshots

![image](https://user-images.githubusercontent.com/745011/87069422-26274200-c1e5-11ea-841a-0b939deb25a3.png)

## Your Environment

Most recent version of amundsenfrontendlibrary.

**Comment by ttannis** [comment] 2020-07-09 21:49
Not a bug, just wasn't written that way intentionally because we didn't have a use case. :)
https://github.com/lyft/amundsenfrontendlibrary/pull/506

**Comment by ttannis** [comment] 2020-07-09 21:51
Available on master, and will be included in the next frontend release.

**Comment by jonhehir** [comment] 2020-07-09 21:52
Wow, very quick. Thank you!

**Closed by ttannis** 2020-07-09 21:51 UTC
Labels: Project: Frontend, Status: Review Needed, good first issue, help wanted, keep fresh
