### ISSUE TITLE
amundsenmetadata crashes while running a local build on Windows

### ISSUE THREAD

**Issue by tusharsadhwani** [lyft/amundsen#518] opened 2020-06-19 07:30 UTC
## Current Behavior
```
amundsenmetadata    | 2020-06-19T07:12:55+0000.918 [INFO] __init__.create_app:78 (1:MainThread) - Created app with config name metadata_service.config.LocalConfig
amundsenmetadata    | 2020-06-19T07:12:55+0000.918 [INFO] __init__.create_app:79 (1:MainThread) - Using backend metadata_service.proxy.neo4j_proxy.Neo4jProxy
amundsenmetadata    |  * Serving Flask app "metadata_service" (lazy loading)
amundsenmetadata    |  * Environment: production
amundsenmetadata    |    WARNING: Do not use the development server in a production environment.
amundsenmetadata    |    Use a production WSGI server instead.
amundsenmetadata    |  * Debug mode: on
amundsenmetadata    | 2020-06-19T07:12:56+0000.128 [INFO] _internal._log:122 (1:MainThread) -  * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
amundsenmetadata    | 2020-06-19T07:12:56+0000.134 [INFO] _internal._log:122 (1:MainThread) -  * Restarting with stat
amundsenmetadata    | Traceback (most recent call last):
amundsenmetadata    |   File "metadata_service/metadata_wsgi.py", line 14, in <module>
amundsenmetadata    |     application.run(host='0.0.0.0', port=5002)
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 943, in run
amundsenmetadata    |     run_simple(host, port, self, **options)
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 1007, in run_simple
amundsenmetadata    |     run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
amundsenmetadata    |     sys.exit(reloader.restart_with_reloader())
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
amundsenmetadata    |     exit_code = subprocess.call(args, env=new_environ, close_fds=False)
amundsenmetadata    |   File "/usr/local/lib/python3.7/subprocess.py", line 339, in call
amundsenmetadata    |     with Popen(*popenargs, **kwargs) as p:
amundsenmetadata    |   File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
amundsenmetadata    |     restore_signals, start_new_session)
amundsenmetadata    |   File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
amundsenmetadata    |     raise child_exception_type(errno_num, err_msg, err_filename)
amundsenmetadata    | OSError: [Errno 8] Exec format error: '/app/metadata_service/metadata_wsgi.py'
amundsenmetadata exited with code 1
```
## Steps to Reproduce
1. clone the repository
2. run `docker-compose -f ./docker-amundsen-local.yml up`

## Current Environment
- Windows 10 version 1903
- Running the commands via Powershell

**Comment by jornh** [comment] 2020-06-19 12:14
https://github.com/lyft/amundsenmetadatalibrary/blob/master/requirements.txt#L63 says we're running Werkzeug `0.15.3`

This: https://github.com/pallets/werkzeug/issues/1482 could be the issue, it was reported on `0.15.0` and resolved in `0.15.5` ... but the changelog https://werkzeug.palletsprojects.com/en/0.16.x/changes/#version-0-16-1 suggests that there's another Windows related fix later in `0.15.6`.

Try bumping the Werkzeug version to `0.16.1` or something and test if that resolves it ...

**Comment by tusharsadhwani** [comment] 2020-06-19 12:53
> Try bumping the Werkzeug version to `0.16.1` or something and test if that resolves it ...

bumped to 1.16.1, and it just worked.

As the next step, How do I get this patched into the project itself? Do I just create a simple PR bumping the version, or are there any other caveats.

**Comment by feng-tao** [comment] 2020-06-19 17:47
Feel free to submit a pr. Thanks @jornh for the RC as well!

**Comment by feng-tao** [comment] 2020-06-21 22:01
it seems that the issue is resolved, feel free to reopen if that's not the case.

**Closed by feng-tao** 2020-06-21 22:01 UTC
